version: "2"
services:
    app:
        build:
            context: .
            dockerfile: dev.Dockerfile
        ports:
            - 5000:5000
        volumes:
            - .:/usr/src/app/
    redis:
        image: redis:5.0.3
        ports:
            - "6379"
